# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_mu_cpp <- function(Y, FF, Phi, sigma2, mu_0, sigma_mu2) {
    .Call(`_tacfa_sample_mu_cpp`, Y, FF, Phi, sigma2, mu_0, sigma_mu2)
}

sample_sigma2_cpp <- function(Y, FF, Phi, mu, a_sigma2, b_sigma2) {
    .Call(`_tacfa_sample_sigma2_cpp`, Y, FF, Phi, mu, a_sigma2, b_sigma2)
}

sample_phi_cpp <- function(Y, FF, mu, sigma2, mu_phi, sigma_phi2, phi_fixed, phi_factor) {
    .Call(`_tacfa_sample_phi_cpp`, Y, FF, mu, sigma2, mu_phi, sigma_phi2, phi_fixed, phi_factor)
}

sample_Psi_cpp <- function(beta, n_vk, anchor_words, anchor_prob, nonanchor_prob) {
    .Call(`_tacfa_sample_Psi_cpp`, beta, n_vk, anchor_words, anchor_prob, nonanchor_prob)
}

sample_Z_cpp <- function(W, Theta, log_Psi_full) {
    .Call(`_tacfa_sample_Z_cpp`, W, Theta, log_Psi_full)
}

comp_Theta_cpp <- function(tau_full, FF, Gamma) {
    .Call(`_tacfa_comp_Theta_cpp`, tau_full, FF, Gamma)
}

comp_n_vk_cpp <- function(W, Z, V, K) {
    .Call(`_tacfa_comp_n_vk_cpp`, W, Z, V, K)
}

make_Z_cpp <- function(Theta, M) {
    .Call(`_tacfa_make_Z_cpp`, Theta, M)
}

make_W_cpp <- function(Psi_full, Z) {
    .Call(`_tacfa_make_W_cpp`, Psi_full, Z)
}

comp_log_p_FF_cpp <- function(Y, n_ik, FF, mu, R_inv, sigma2, Phi, Gamma, tau, FF_Gamma) {
    .Call(`_tacfa_comp_log_p_FF_cpp`, Y, n_ik, FF, mu, R_inv, sigma2, Phi, Gamma, tau, FF_Gamma)
}

comp_grad_log_p_FF_cpp <- function(Y, n_ik, FF, mu, R_inv, sigma2, Phi, Gamma, tau_full, FF_Gamma) {
    .Call(`_tacfa_comp_grad_log_p_FF_cpp`, Y, n_ik, FF, mu, R_inv, sigma2, Phi, Gamma, tau_full, FF_Gamma)
}

comp_log_p_gamma_cpp <- function(FF_Gamma, gamma, n_ik, tau_full, mu_gamma, sigma_gamma2) {
    .Call(`_tacfa_comp_log_p_gamma_cpp`, FF_Gamma, gamma, n_ik, tau_full, mu_gamma, sigma_gamma2)
}

comp_grad_log_p_gamma_cpp <- function(FF, FF_Gamma, gamma, n_ik, tau_full, mu_gamma, sigma_gamma2, gamma_fixed, gamma_factor) {
    .Call(`_tacfa_comp_grad_log_p_gamma_cpp`, FF, FF_Gamma, gamma, n_ik, tau_full, mu_gamma, sigma_gamma2, gamma_fixed, gamma_factor)
}

comp_log_p_tau_cpp <- function(FF_Gamma, n_ik, tau, tau_full, mu_tau, sigma_tau2) {
    .Call(`_tacfa_comp_log_p_tau_cpp`, FF_Gamma, n_ik, tau, tau_full, mu_tau, sigma_tau2)
}

comp_grad_log_p_tau_cpp <- function(FF_Gamma, n_ik, tau, tau_full, mu_tau, sigma_tau2, topic_baseline) {
    .Call(`_tacfa_comp_grad_log_p_tau_cpp`, FF_Gamma, n_ik, tau, tau_full, mu_tau, sigma_tau2, topic_baseline)
}

